# Generated by Django 6.0.5 on 2026-05-25 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_discipline_rolechoice_user_job_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reset_password_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_password_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
