# Generated by Codex on 2026-05-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_reset_password_otp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='reset_password_otp',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
