# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_reset_password_otp'),
        ('journals', '0009_alter_submissionfile_file_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='classifications',
            field=models.ManyToManyField(
                blank=True,
                related_name='users',
                to='journals.classification',
            ),
        ),
    ]
