# Generated by Django 6.0.5 on 2026-05-12 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='description',
        ),
    ]
