# Generated by Django 6.0.5 on 2026-05-12 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_remove_articletype_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletype',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='display_order',
        ),
    ]
