# Generated by Django 6.0.5 on 2026-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_articletype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='is_open_access_allowed',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='requires_cover_letter',
        ),
        migrations.RemoveField(
            model_name='articletype',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='articletype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
