# Generated by Django 6.0.5 on 2026-05-12 05:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_remove_articletype_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articletype',
            name='description',
        ),
        migrations.AddField(
            model_name='articletype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='articletype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
