# Generated by Django 6.0.5 on 2026-05-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_remove_articletype_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributorRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('is_corresponding_author', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor_roles', models.ManyToManyField(blank=True, related_name='submission_authors', to='journals.contributorrole')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='journals.submission')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
