# Generated by Django 6.0.5 on 2026-05-18 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0006_contributorrole_submissionauthor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='submissions/files/')),
                ('original_filename', models.CharField(blank=True, max_length=500)),
                ('file_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionFileType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_multiple', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Submission File Type',
                'verbose_name_plural': 'Submission File Types',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='submission',
            name='cover_letter_file',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='manuscript_file',
        ),
        migrations.AddConstraint(
            model_name='submissionauthor',
            constraint=models.UniqueConstraint(condition=models.Q(('is_corresponding_author', True)), fields=('submission',), name='unique_corresponding_author_per_submission'),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_files', to='journals.submission'),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='file_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='journals.submissionfiletype'),
        ),
    ]
