# Generated by Django 6.0.5 on 2026-05-20 07:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0007_submissionfile_submissionfiletype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='classification',
            name='subject',
        ),
        migrations.AddField(
            model_name='classification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classification',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
