# Generated by Codex on 2026-06-01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_classifications'),
        ('journals', '0009_alter_submissionfile_file_size_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionReviewerAssignment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                (
                    'assigned_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='assigned_reviewers',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'reviewer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='review_assignments',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'submission',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reviewer_assignments',
                        to='journals.submission',
                    ),
                ),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='submissionreviewerassignment',
            constraint=models.UniqueConstraint(
                fields=('submission', 'reviewer'),
                name='unique_reviewer_assignment_per_submission',
            ),
        ),
    ]
