# Generated by Codex on 2026-06-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0012_submissionreviewerassignment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreviewerassignment',
            name='reviewer_response_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
