# Generated by Django 6.0.5 on 2026-07-07 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0015_submission_manuscript_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissionreviewerassignment',
            name='reviewer_report_reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
